spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/promotion_db
    username: root
    password: slsZ1XmB
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always